// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type VirtualKeyInitParameters struct {

	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools []*string `json:"allowedPools,omitempty" tf:"allowed_pools,omitempty"`

	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod *string `json:"budgetPeriod,omitempty" tf:"budget_period,omitempty"`

	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `json:"issueAwsCredential,omitempty" tf:"issue_aws_credential,omitempty"`

	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents *float64 `json:"maxBudgetCents,omitempty" tf:"max_budget_cents,omitempty"`

	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

type VirtualKeyObservation struct {

	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools []*string `json:"allowedPools,omitempty" tf:"allowed_pools,omitempty"`

	// AWS-style access key id, when issue_aws_credential is true. Returned only at creation.
	AwsAccessKeyID *string `json:"awsAccessKeyId,omitempty" tf:"aws_access_key_id,omitempty"`

	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod *string `json:"budgetPeriod,omitempty" tf:"budget_period,omitempty"`

	// Epoch seconds the key was minted.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `json:"issueAwsCredential,omitempty" tf:"issue_aws_credential,omitempty"`

	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents *float64 `json:"maxBudgetCents,omitempty" tf:"max_budget_cents,omitempty"`

	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

type VirtualKeyParameters struct {

	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	// +kubebuilder:validation:Optional
	AllowedPools []*string `json:"allowedPools,omitempty" tf:"allowed_pools,omitempty"`

	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	// +kubebuilder:validation:Optional
	BudgetPeriod *string `json:"budgetPeriod,omitempty" tf:"budget_period,omitempty"`

	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	// +kubebuilder:validation:Optional
	IssueAwsCredential *bool `json:"issueAwsCredential,omitempty" tf:"issue_aws_credential,omitempty"`

	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	// +kubebuilder:validation:Optional
	MaxBudgetCents *float64 `json:"maxBudgetCents,omitempty" tf:"max_budget_cents,omitempty"`

	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	// +kubebuilder:validation:Optional
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	// +kubebuilder:validation:Optional
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`
}

// VirtualKeySpec defines the desired state of VirtualKey
type VirtualKeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VirtualKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VirtualKeyInitParameters `json:"initProvider,omitempty"`
}

// VirtualKeyStatus defines the observed state of VirtualKey.
type VirtualKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VirtualKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VirtualKey is the Schema for the VirtualKeys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,busbar}
type VirtualKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VirtualKeySpec   `json:"spec"`
	Status VirtualKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VirtualKeyList contains a list of VirtualKeys
type VirtualKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VirtualKey `json:"items"`
}

// Repository type metadata.
var (
	VirtualKey_Kind             = "VirtualKey"
	VirtualKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VirtualKey_Kind}.String()
	VirtualKey_KindAPIVersion   = VirtualKey_Kind + "." + CRDGroupVersion.String()
	VirtualKey_GroupVersionKind = CRDGroupVersion.WithKind(VirtualKey_Kind)
)

func init() {
	SchemeBuilder.Register(&VirtualKey{}, &VirtualKeyList{})
}
