// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type VirtualKeyInitParameters struct {

	// (List of String) Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools []*string `json:"allowedPools,omitempty" tf:"allowed_pools,omitempty"`

	// (Boolean) Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's state reads "disabled").
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with expires_in) and is always computed from the mint response. Changing it replaces the key.
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// time + this. Mutually exclusive with expires_at. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn *string `json:"expiresIn,omitempty" tf:"expires_in,omitempty"`

	// provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `json:"issueAwsCredential,omitempty" tf:"issue_aws_credential,omitempty"`

	// time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// readable label (<= 256 chars). Immutable; changing it replaces the key.
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// provision target: the EXISTING parent group under which group is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`
}

type VirtualKeyObservation struct {

	// (List of String) Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools []*string `json:"allowedPools,omitempty" tf:"allowed_pools,omitempty"`

	// style access key id, when issue_aws_credential is true. Returned only at creation.
	// AWS-style access key id, when issue_aws_credential is true. Returned only at creation.
	AwsAccessKeyID *string `json:"awsAccessKeyId,omitempty" tf:"aws_access_key_id,omitempty"`

	// (Number) Epoch seconds the key was minted.
	// Epoch seconds the key was minted.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's state reads "disabled").
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with expires_in) and is always computed from the mint response. Changing it replaces the key.
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// time + this. Mutually exclusive with expires_at. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn *string `json:"expiresIn,omitempty" tf:"expires_in,omitempty"`

	// provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// provisioned its bound group leaf (self-service). Known only at creation.
	// Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
	GroupProvisioned *bool `json:"groupProvisioned,omitempty" tf:"group_provisioned,omitempty"`

	// assigned key id (e.g. vk_0123456789abcdef).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `json:"issueAwsCredential,omitempty" tf:"issue_aws_credential,omitempty"`

	// time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// readable label (<= 256 chars). Immutable; changing it replaces the key.
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// provision target: the EXISTING parent group under which group is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// (String) Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
	// Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type VirtualKeyParameters struct {

	// (List of String) Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	// +kubebuilder:validation:Optional
	AllowedPools []*string `json:"allowedPools,omitempty" tf:"allowed_pools,omitempty"`

	// (Boolean) Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's state reads "disabled").
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with expires_in) and is always computed from the mint response. Changing it replaces the key.
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
	// +kubebuilder:validation:Optional
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// time + this. Mutually exclusive with expires_at. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	// +kubebuilder:validation:Optional
	ExpiresIn *string `json:"expiresIn,omitempty" tf:"expires_in,omitempty"`

	// provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	// +kubebuilder:validation:Optional
	IssueAwsCredential *bool `json:"issueAwsCredential,omitempty" tf:"issue_aws_credential,omitempty"`

	// time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// readable label (<= 256 chars). Immutable; changing it replaces the key.
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// provision target: the EXISTING parent group under which group is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`
}

// VirtualKeySpec defines the desired state of VirtualKey
type VirtualKeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VirtualKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VirtualKeyInitParameters `json:"initProvider,omitempty"`
}

// VirtualKeyStatus defines the observed state of VirtualKey.
type VirtualKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VirtualKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VirtualKey is the Schema for the VirtualKeys API. A governance virtual key (busbar >= 1.5.0): a mintable, revocable, EXPIRING signed-token credential, optionally bound to a groups: bucket that carries all budget and rate enforcement (POST/GET/PATCH/DELETE /api/v1/admin/keys). The signed token is returned by busbar only once, at creation, and is stored in state as a sensitive value; refreshes update metadata (group/enabled/state) but never the token. Requires governance to be enabled on the gateway.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,busbar}
type VirtualKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VirtualKeySpec   `json:"spec"`
	Status VirtualKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VirtualKeyList contains a list of VirtualKeys
type VirtualKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VirtualKey `json:"items"`
}

// Repository type metadata.
var (
	VirtualKey_Kind             = "VirtualKey"
	VirtualKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VirtualKey_Kind}.String()
	VirtualKey_KindAPIVersion   = VirtualKey_Kind + "." + CRDGroupVersion.String()
	VirtualKey_GroupVersionKind = CRDGroupVersion.WithKind(VirtualKey_Kind)
)

func init() {
	SchemeBuilder.Register(&VirtualKey{}, &VirtualKeyList{})
}
